[package]
name = "add_symbol_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0"
quote = "1.0"
llvm-sys = "140"

[lib]
proc-macro = true
