[book]
authors = ["The pivot-lang Authors"]
language = "en"
multilingual = true
src = "src"
title = "Pivot Lang"

[build]
create-missing = false

[output.html]
git-repository-url = "https://github.com/Pivot-Studio/pivot-lang"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/Pivot-Studio/pivot-lang/master/book/{path}"
